apiVersion: v1
kind: Service
metadata:
  name: twit-k8s-service
spec:
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
  selector:
    app: twit-app  # Matches the pods with this label
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 8080  # Port on the container to forward traffic to
