version: '3.8'

services:
  springboot-app:
    image: webflix-image:latest
    container_name: webflix-app-container
    ports:
      - "8072:8072"
    environment:
      SPRING_PROFILES_ACTIVE: dev # Optional: Set the active Spring profile
    networks:
      - app-net

networks:
  app-net:
