apiVersion: v1
kind: Service
metadata:
  name: twit-app-service
spec:
  type: NodePort
  selector:
    app: twit-app
  ports:
    - protocol: TCP
      port: 80           # Port on which the service will be exposed
      targetPort: 8070   # Port on which the application container is listening
      nodePort: 31464    # Port on each node to access the service
